-- =============================================================================
-- 012_in_search_of.sql
-- =============================================================================
-- Adds "In Search Of" (ISO) listings — buyer-posted requests for a specific
-- artwork. Same listings table, gated by listing_type='iso'. Existing sale
-- rows stay listing_type='sale' (the default).
--
-- ISO listings have looser required fields:
--   - asking_price_usd, shipping_offered, coa_included: not required
--   - artist_name OR artwork_title: at least one required (vs both required
--     for sale listings)
--   - budget_min_usd / budget_max_usd: optional, buyer's price expectation
-- =============================================================================

-- 1. Add the type discriminator and the budget columns.
alter table public.listings
  add column if not exists listing_type   text not null default 'sale'
    check (listing_type in ('sale', 'iso')),
  add column if not exists budget_min_usd numeric
    check (budget_min_usd is null or budget_min_usd >= 0),
  add column if not exists budget_max_usd numeric
    check (budget_max_usd is null or budget_max_usd >= 0);

create index if not exists listings_listing_type_idx
  on public.listings (listing_type);

-- 2. Relax NOT NULL on fields that don't apply to ISO posts. Existing rows
-- keep their values; new ISO rows can omit them.
alter table public.listings alter column artist_name      drop not null;
alter table public.listings alter column artwork_title    drop not null;
alter table public.listings alter column asking_price_usd drop not null;
alter table public.listings alter column shipping_offered drop not null;
alter table public.listings alter column coa_included     drop not null;

-- 3. Drop the individual column-level checks that enforced presence/values
-- only at the column level — we'll replace them with one type-aware check.
-- (Names auto-generated by Postgres for "column check (...)" syntax —
--  use if-exists so the migration is idempotent even if names differ.)
alter table public.listings drop constraint if exists listings_asking_price_usd_check;
alter table public.listings drop constraint if exists listings_shipping_offered_check;
alter table public.listings drop constraint if exists listings_coa_included_check;

-- 4. One unified check that enforces "right fields for the right type."
alter table public.listings drop constraint if exists listings_required_by_type;
alter table public.listings add constraint listings_required_by_type check (
  case
    when listing_type = 'sale' then
      artist_name      is not null and
      artwork_title    is not null and
      asking_price_usd is not null and asking_price_usd >= 0 and
      shipping_offered is not null and shipping_offered in ('Yes','No') and
      coa_included     is not null and coa_included     in ('Yes','No')
    when listing_type = 'iso' then
      coalesce(nullif(trim(artist_name), ''), nullif(trim(artwork_title), '')) is not null and
      (budget_min_usd is null or budget_max_usd is null or budget_max_usd >= budget_min_usd)
    else false
  end
);

-- 5. Composite indexes that cover the new listing_type filter in the
-- public-catalog queries (both tabs).
create index if not exists listings_catalog_type_status_created_idx
  on public.listings (listing_type, moderation_status, status, created_at desc);
