// =============================================================================
// return-trail.js — "Continue where you left off" after sign-up / sign-in
// =============================================================================
// When an unsigned visitor lands on a seller page (or listing detail) and
// clicks "Sign in" or "Create account", we want them to land back on that
// page once they're authenticated — otherwise they hit the generic portal
// dashboard and lose the context that brought them in.
//
// Two cooperating mechanisms:
//   1. Query param `?returnTo=<url>` on the /portal/ links. Works for the
//      simple sign-in flow that completes without email confirmation.
//   2. localStorage breadcrumb. Survives the signup → email-confirmation
//      redirect dance (which drops the query param, since the email link is
//      generated by Supabase with a hard-coded redirect target).
//
// The portal reads both signals on dashboard load. If found, it shows a
// "Continue to <label> →" banner instead of auto-redirecting, so the user
// learns the portal exists but still has one tap back to where they were.
// =============================================================================

const KEY = "cc_returnTo";
const MAX_AGE_MS = 24 * 60 * 60 * 1000;  // 24 hours — stale trails self-clean

/**
 * Arm the trail on the current public page. Call this from seller.html /
 * listing.html / the auth-prompt modal when an unsigned viewer is looking
 * at content that requires sign-in to fully access.
 *
 * Two things happen:
 *   1. Every <a href="/portal/..."> link on the page gets `?returnTo=<here>`
 *      appended to its href (preserving any other query params).
 *   2. Each of those links also gets a click handler that writes the
 *      breadcrumb to localStorage, so the trail survives email confirmation.
 *
 * Safe to call multiple times — already-armed links are skipped.
 *
 * @param {string} label - human-readable label shown in the "Continue to X"
 *   banner. Examples: "@johndoe's seller page", "the listing you were viewing".
 */
export function armReturnTrail(label) {
  const here = location.pathname + location.search;
  const encoded = encodeURIComponent(here);

  const links = document.querySelectorAll('a[href]');
  for (const a of links) {
    const href = a.getAttribute("href");
    if (!href) continue;
    // Only rewrite same-origin /portal links — not "/portal" in a longer path
    // and not absolute https://other.site/portal/.
    if (!(href === "/portal" || href === "/portal/" || href.startsWith("/portal/") || href.startsWith("/portal?"))) continue;
    if (href.includes("returnTo=")) continue;
    const sep = href.includes("?") ? "&" : "?";
    a.href = href + sep + "returnTo=" + encoded;
    // Also stash the breadcrumb at click-time so it survives the signup →
    // email confirmation round-trip (which loses query params).
    a.addEventListener("click", () => writeBreadcrumb(here, label));
  }
}

function writeBreadcrumb(url, label) {
  try {
    localStorage.setItem(KEY, JSON.stringify({
      url, label: label || "", ts: Date.now(),
    }));
  } catch (e) { /* private mode etc — ignore */ }
}

/**
 * Read the current return-trail breadcrumb on the portal side.
 * Returns { url, label } or null.
 *
 * Prefers the URL `?returnTo=` query param (fresh from a click) but falls
 * back to localStorage (which survives email-confirmation redirects).
 * Only honors paths that start with `/` (same-origin) — no open redirects.
 */
export function readReturnTrail() {
  // 1) URL query param — set by armReturnTrail when the user clicked a CTA
  try {
    const params = new URLSearchParams(location.search);
    const fromQuery = params.get("returnTo");
    if (fromQuery && isSafePath(fromQuery)) {
      // Cross-reference localStorage to pick up the label (which the query
      // param doesn't carry to keep URLs short).
      let label = "";
      try {
        const raw = localStorage.getItem(KEY);
        if (raw) {
          const b = JSON.parse(raw);
          if (b && b.url === fromQuery) label = b.label || "";
        }
      } catch (e) {}
      return { url: fromQuery, label };
    }
  } catch (e) {}

  // 2) localStorage fallback — set by armReturnTrail's click handler
  try {
    const raw = localStorage.getItem(KEY);
    if (!raw) return null;
    const b = JSON.parse(raw);
    if (!b || !b.url) return null;
    if (b.ts && (Date.now() - b.ts) > MAX_AGE_MS) {
      clearReturnTrail();
      return null;
    }
    if (!isSafePath(b.url)) return null;
    return { url: b.url, label: b.label || "" };
  } catch (e) {
    return null;
  }
}

function isSafePath(p) {
  // Must be a same-origin path. Disallow protocol-relative `//evil.com` and
  // any absolute URL (http://, https://, javascript:, data:, etc.).
  return typeof p === "string"
      && p.startsWith("/")
      && !p.startsWith("//");
}

export function clearReturnTrail() {
  try { localStorage.removeItem(KEY); } catch (e) {}
}
