#!/usr/bin/env python3
# =============================================================================
# og_tagline_swap.py
# =============================================================================
# One-shot utility: swap the tagline text on assets/og-image.png while keeping
# the logo card, feature badges, and canvascircle.art footer intact.
#
# Why this exists:
#   The original og-image.png was generated by a previous workflow that we no
#   longer have. To update just the tagline (e.g. when the brand language
#   changes), we paint over the tagline strip and re-render. This script is
#   idempotent — run it whenever the NEW_TAGLINE constant changes.
#
# Usage:
#   1. Edit NEW_TAGLINE below.
#   2. python3 og_tagline_swap.py
#   3. Commit the updated og-image.png.
#
# Requires Pillow:  pip install --break-system-packages pillow
# =============================================================================

from PIL import Image, ImageDraw, ImageFont
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "og-image.png")
DST  = os.path.join(HERE, "og-image.png")  # overwrite in place

# ---- Edit this string when the tagline changes -------------------------------
NEW_TAGLINE = "A modern art listing platform built for collectors"
# -----------------------------------------------------------------------------

# Canvas / brand constants — match the original og-image.png design.
BG = (245, 241, 234)
FG = (26, 26, 26)            # matches site's --fg (#1a1a1a)
# Coordinates of the tagline strip in the original 1200x630 image. The clear
# box is generous on both sides; the text is then drawn centered horizontally
# in the original tagline x-range and vertically in the clear box.
CLEAR_BOX     = (180, 385, 1020, 445)   # (x0, y0, x1, y1)
TEXT_X_RANGE  = (235, 966)              # original tagline horizontal span
FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf",
    "/Library/Fonts/Georgia.ttf",                           # macOS
    "/System/Library/Fonts/Supplemental/Georgia.ttf",       # macOS newer
    "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",     # Linux fallback
]


def pick_font_path():
    for p in FONT_CANDIDATES:
        if os.path.exists(p):
            return p
    sys.exit("ERROR: no serif font found. Install Liberation Serif or edit FONT_CANDIDATES.")


def main():
    img = Image.open(SRC).convert("RGB")
    W, H = img.size
    draw = ImageDraw.Draw(img)

    # 1) Paint over the existing tagline.
    draw.rectangle(CLEAR_BOX, fill=BG)

    # 2) Pick the largest font size that still fits the available width.
    font_path = pick_font_path()
    max_w = CLEAR_BOX[2] - CLEAR_BOX[0] - 40  # 20px padding each side
    chosen = None
    for size in range(48, 22, -1):
        f = ImageFont.truetype(font_path, size)
        bbox = draw.textbbox((0, 0), NEW_TAGLINE, font=f)
        if (bbox[2] - bbox[0]) <= max_w:
            chosen = (size, f, bbox)
            break
    if chosen is None:
        sys.exit("ERROR: tagline doesn't fit even at size 22. Shorten it.")
    size, f, bbox = chosen

    # 3) Center the text horizontally in the original x-range and vertically
    #    in the clear box.
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]
    cx = (TEXT_X_RANGE[0] + TEXT_X_RANGE[1]) / 2
    x  = int(cx - text_w / 2 - bbox[0])
    y  = int((CLEAR_BOX[1] + CLEAR_BOX[3]) / 2 - text_h / 2 - bbox[1])

    draw.text((x, y), NEW_TAGLINE, font=f, fill=FG)
    img.save(DST, optimize=True)
    print(f"OK: tagline updated. font_size={size}, text_w={text_w}px, drawn at ({x}, {y})")


if __name__ == "__main__":
    main()
